export const items = [  
{  
id: 1,  
name: "Classic Swarovski Sparkle",  
blurb: "A timeless, ultra-reflective crystal that catches the light with every smile.",  
rating: 5,  
emoji: "💎",  
},  
{  
id: 2,  
name: "18K Gold Star Charm",  
blurb: "Bold, Y2K-inspired luxury bonded safely to your enamel for an iconic flash.",  
rating: 5,  
emoji: "⭐",  
},  
{  
id: 3,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},  
{  
id: 4,  
name: "Classic Swarovski Sparkle",  
blurb: "A timeless, ultra-reflective crystal that catches the light with every smile.",  
rating: 5,  
emoji: "💎",  
},  
{  
id: 5,  
name: "18K Gold Star Charm",  
blurb: "Bold, Y2K-inspired luxury bonded safely to your enamel for an iconic flash.",  
rating: 5,  
emoji: "⭐",  
},  
{  
id: 6,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},  
{  
id: 7,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},
{  
id: 8,  
name: "Classic Swarovski Sparkle",  
blurb: "A timeless, ultra-reflective crystal that catches the light with every smile.",  
rating: 5,  
emoji: "💎",  
},  
{  
id: 9,  
name: "18K Gold Star Charm",  
blurb: "Bold, Y2K-inspired luxury bonded safely to your enamel for an iconic flash.",  
rating: 5,  
emoji: "⭐",  
},  
{  
id: 10,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},  
{  
id: 11,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
}, 
{  
id: 12,  
name: "Classic Swarovski Sparkle",  
blurb: "A timeless, ultra-reflective crystal that catches the light with every smile.",  
rating: 5,  
emoji: "💎",  
},  
{  
id: 13,  
name: "18K Gold Star Charm",  
blurb: "Bold, Y2K-inspired luxury bonded safely to your enamel for an iconic flash.",  
rating: 5,  
emoji: "⭐",  
},  
{  
id: 14,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},  
{  
id: 15,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},
{  
id: 16,  
name: "Classic Swarovski Sparkle",  
blurb: "A timeless, ultra-reflective crystal that catches the light with every smile.",  
rating: 5,  
emoji: "💎",  
},  
{  
id: 17,  
name: "18K Gold Star Charm",  
blurb: "Bold, Y2K-inspired luxury bonded safely to your enamel for an iconic flash.",  
rating: 5,  
emoji: "⭐",  
},  
{  
id: 18,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
}, 
{
  id: 19,  
name: "Classic Swarovski Sparkle",  
blurb: "A timeless, ultra-reflective crystal that catches the light with every smile.",  
rating: 5,  
emoji: "💎",  
},  
{  
id: 20,  
name: "18K Gold Star Charm",  
blurb: "Bold, Y2K-inspired luxury bonded safely to your enamel for an iconic flash.",  
rating: 5,  
emoji: "⭐",  
},  
{  
id: 21,  
name: "Minimalist Opal Dot",  
blurb: "Subtle, iridescent color shifts that bring a unique, modern edge to your look.",  
rating: 4,  
emoji: "✨",  
},   
  
];

